opt_in_rules:
- anyobject_protocol
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- convenience_type
- discarded_notification_center_observer
- discouraged_object_literal
- empty_collection_literal
- empty_count
- empty_string
- explicit_init
- explicit_self
- fallthrough
- fatal_error_message
- file_name_no_space
- file_types_order
- first_where
- flatmap_over_map_reduce
- force_unwrapping
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- last_where
- let_var_whitespace
- literal_expression_end_indentation
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- number_separator
- operator_usage_whitespace
- overridden_super_call
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- prefixed_toplevel_constant
- private_action
- private_outlet
- redundant_type_annotation
- required_enum_case
- sorted_first_last
- sorted_imports
- static_operator
- switch_case_on_newline
- toggle_bool
- type_contents_order
- unavailable_function
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- unused_declaration
- unused_import
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- yoda_condition

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

closure_body_length:
    warning: 50

force_cast: error
force_try: error

identifier_name:
  excluded:
    - id
  min_length: 2
  max_length: 60

implicit_return:
    included: [getter, closure]

private_outlet:
    allow_private_set: true

line_length:
    ignores_urls: true

function_body_length:
    warning: 80
    error: 160

function_parameter_count:
    warning: 7
    error: 10

multiline_arguments:
    only_enforce_after_first_closure_on_first_line: true

nesting:
    type_level: 2

type_body_length:
    warning: 500
    error: 800

type_contents_order:
    order: [[SwiftLintFramework.TypeContent.case], [SwiftLintFramework.TypeContent.typeAlias, SwiftLintFramework.TypeContent.associatedType], [SwiftLintFramework.TypeContent.subtype], [SwiftLintFramework.TypeContent.ibInspectable], [SwiftLintFramework.TypeContent.ibOutlet], [SwiftLintFramework.TypeContent.typeProperty], [SwiftLintFramework.TypeContent.instanceProperty], [SwiftLintFramework.TypeContent.initializer], [SwiftLintFramework.TypeContent.typeMethod], [SwiftLintFramework.TypeContent.viewLifeCycleMethod], [SwiftLintFramework.TypeContent.ibAction], [SwiftLintFramework.TypeContent.otherMethod], [SwiftLintFramework.TypeContent.subscript], [SwiftLintFramework.TypeContent.deinitializer]]

type_name:
    max_length: 60

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"

